### ISSUE TITLE
VERSION 3 checklist

### ISSUE THREAD

**Issue by evilz** [evilz/vscode-reveal#109]
- [x]  new webview api for split view
- [x]  new activitybar for slides explorer
- [x]  showRevealJSInBrowser
- [x]  stopServer
- [ ]  container.goToSlide
- [x]  exportPDF
- [x]  exportHTM
- [x]  new template

## PLUGINS

- [x]  plugin marked
- [x]  markdown
- [x]  highlight
- [x]  search
- [x]  zoom
- [x]  notes
- [x]  chalkboard
- [x]  Chart
- [x]  csv2chart
- [x]  embed-tweet
- [x]  menu
- [x]  math.js
- [x]  title-footer
- [x]  reveal-code-focus

- [ ] Readme

**Comment by qcho** [comment]
Maybe mermaid? #103

**Comment by evilz** [comment]
mermaid is now in 4.x.x
